name: smartmower
description: "A new Flutter project."
version: 1.0.0+1
environment:
  sdk: ">=3.5.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Firebase dependencies
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.3.1
  
  # Collection dependency downgraded to be compatible with flutter_test
  collection: ^1.18.0

  flutter_facebook_auth: ^7.1.1
  google_sign_in: ^5.4.2
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  # Add flutter_launcher_icons to generate app icons
  flutter_launcher_icons: ^0.11.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/sm-logo-appp.png"  # Path to your app icon
  

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/white-logo.png
    - assets/images/google_icon.png
    - assets/images/facebook_icon.png
    - assets/images/github_icon.png  

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
